// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dabmjhhgnorjscxyazuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhYm1qaGhnbm9yanNjeHlhenVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NjU0NzMsImV4cCI6MjA2OTQ0MTQ3M30.XrqFo7l4F7ijIVBczXPTe5U4nXcT3ttMCfPD5o2x9Rw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});